on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Downgrade mingw to 11.2.0
        run: choco install mingw --version 11.2.0 --allow-downgrade
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}